name: student-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-inference-server-http==1.5.1
      - pandas==2.2.2
      - numpy==2.4.6
      - scikit-learn
      - joblib